package com.tmall.dataobject;

public class ItemInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.state
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.item_id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.image1
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private String image1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.image2
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private String image2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.image3
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private String image3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.image4
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private String image4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_info.origin_price
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    private Double originPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.id
     *
     * @return the value of item_info.id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.id
     *
     * @param id the value for item_info.id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.state
     *
     * @return the value of item_info.state
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.state
     *
     * @param state the value for item_info.state
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.item_id
     *
     * @return the value of item_info.item_id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.item_id
     *
     * @param itemId the value for item_info.item_id
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.image1
     *
     * @return the value of item_info.image1
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.image1
     *
     * @param image1 the value for item_info.image1
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.image2
     *
     * @return the value of item_info.image2
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.image2
     *
     * @param image2 the value for item_info.image2
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.image3
     *
     * @return the value of item_info.image3
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.image3
     *
     * @param image3 the value for item_info.image3
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setImage3(String image3) {
        this.image3 = image3 == null ? null : image3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.image4
     *
     * @return the value of item_info.image4
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public String getImage4() {
        return image4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.image4
     *
     * @param image4 the value for item_info.image4
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setImage4(String image4) {
        this.image4 = image4 == null ? null : image4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_info.origin_price
     *
     * @return the value of item_info.origin_price
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public Double getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_info.origin_price
     *
     * @param originPrice the value for item_info.origin_price
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    public void setOriginPrice(Double originPrice) {
        this.originPrice = originPrice;
    }
}