package com.tmall.dao;

import com.tmall.dataobject.ItemInfoDO;

public interface ItemInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    int insert(ItemInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    int insertSelective(ItemInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    ItemInfoDO selectByPrimaryKey(Integer id);
    ItemInfoDO selectByItemId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    int updateByPrimaryKeySelective(ItemInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Oct 23 12:58:13 CST 2019
     */
    int updateByPrimaryKey(ItemInfoDO record);
}